# Generated by Django 4.2.16 on 2025-05-08 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Caisse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('responsable', models.CharField(max_length=100)),
                ('solde_initial', models.PositiveIntegerField(default=0)),
                ('entree', models.PositiveIntegerField(default=0)),
                ('sortie', models.PositiveIntegerField(default=0)),
                ('solde', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Pages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('contact', models.CharField(max_length=100)),
                ('lien', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PlanDesComptes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('compte_numero', models.CharField(max_length=20)),
                ('libelle', models.CharField(max_length=255)),
            ],
        ),
    ]
