# Generated by Django 4.2.16 on 2025-06-22 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_caisse_created_at_caisse_created_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caisse',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='pages',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='plandescomptes',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
