# Generated by Django 4.2.16 on 2025-08-21 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0005_alter_caisse_created_by_alter_caisse_deleted_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pages',
            name='type',
            field=models.CharField(choices=[('VENTE', 'Vente'), ('SERVICE', 'Service')], default='VENTE', max_length=10),
        ),
    ]
