"""
Django settings for zara_service project.

Generated by 'django-admin startproject' using Django 4.2.23.
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# -------------------------
# Sécurité & Déploiement
# -------------------------
SECRET_KEY = os.environ.get(
    "SECRET_KEY", "django-insecure-jt)lf1208habl**y=6p0!zk4%69#)h1)qo_8jp!_08#kz5#j8i"
)

# ⚠️ mettre DEBUG=False en production
DEBUG = False

ALLOWED_HOSTS = ["zaraservice.pythonanywhere.com"]
CSRF_TRUSTED_ORIGINS = ["https://zaraservice.pythonanywhere.com"]

# -------------------------
# Applications
# -------------------------
INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "django.contrib.humanize",

    # Apps internes
    "services",
    "pwa",
    "clients",
    "encaissement",
    "facturation",
    "vente",
    "common",
    "users",
]

# -------------------------
# Middleware
# -------------------------
MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "zara_service.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [
            BASE_DIR / "templates",
        ],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                "common.context_processors.is_admin_context",
            ],
        },
    },
]

WSGI_APPLICATION = "zara_service.wsgi.application"

# -------------------------
# Base de données MySQL (PythonAnywhere)
# -------------------------
DB_NAME = os.environ.get("DB_NAME", "zaraservice$default")
DB_USER = os.environ.get("DB_USER", "zaraservice")
DB_PASSWORD = os.environ.get("DB_PASSWORD", "")  # à définir dans les variables d’environnement
DB_HOST = os.environ.get("DB_HOST", "zaraservice.mysql.pythonanywhere-services.com")
DB_PORT = os.environ.get("DB_PORT", "3306")

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.mysql",
        "NAME": DB_NAME,
        "USER": DB_USER,
        "PASSWORD": DB_PASSWORD,
        "HOST": DB_HOST,
        "PORT": DB_PORT,
        "OPTIONS": {
            "charset": "utf8mb4",
            "init_command": "SET sql_mode='STRICT_TRANS_TABLES'",
        },
    }
}

# -------------------------
# Authentification
# -------------------------
AUTH_USER_MODEL = "users.CustomUser"

LOGIN_URL = "/login/"
LOGOUT_REDIRECT_URL = "/login/"
LOGIN_REDIRECT_URL = "/"

# -------------------------
# Internationalisation
# -------------------------
LANGUAGE_CODE = "fr-fr"
TIME_ZONE = "Indian/Antananarivo"
USE_I18N = True
USE_TZ = True

# -------------------------
# Fichiers statiques & médias
# -------------------------
STATIC_URL = "/static/"
STATIC_ROOT = BASE_DIR / "staticfiles"
STATICFILES_DIRS = [
    BASE_DIR / "static",
]

MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / "media"

# -------------------------
# Divers
# -------------------------
DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# Envoi email (console en dev, à remplacer en prod)
EMAIL_BACKEND = "django.core.mail.backends.console.EmailBackend"
