# Generated by Django 4.2.23 on 2025-09-01 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, verbose_name="Nom de l'article")),
                ('reference', models.CharField(max_length=50, unique=True, verbose_name='Référence')),
                ('tarif', models.PositiveIntegerField(verbose_name='Tarif (Ar)')),
            ],
        ),
    ]
