# Generated by Django 4.2.23 on 2025-09-01 07:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entreprise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raison_sociale', models.CharField(max_length=255)),
                ('date_debut', models.DateField(blank=True, default=django.utils.timezone.now, null=True)),
                ('page_facebook', models.URLField(blank=True, max_length=255, null=True)),
                ('lien_page', models.URLField(blank=True, null=True)),
                ('activite_produits', models.CharField(blank=True, max_length=255, null=True)),
                ('personne_de_contact', models.CharField(blank=True, max_length=255, null=True)),
                ('lien_profil', models.URLField(blank=True, null=True)),
                ('nif', models.CharField(blank=True, max_length=50, null=True)),
                ('stat', models.CharField(blank=True, max_length=50, null=True)),
                ('rcs', models.CharField(blank=True, max_length=50, null=True)),
                ('adresse', models.TextField(blank=True, null=True)),
                ('telephone', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('fokontany', models.CharField(blank=True, max_length=255, null=True)),
                ('commune', models.CharField(blank=True, max_length=255, null=True)),
                ('region', models.CharField(blank=True, max_length=255, null=True)),
                ('cin_numero', models.CharField(blank=True, max_length=50, null=True)),
                ('date_cin', models.DateField(blank=True, null=True)),
                ('lieu_cin', models.CharField(blank=True, max_length=255, null=True)),
                ('remarque', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
