# Generated by Django 4.2.23 on 2025-09-01 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entreprise',
            name='page_facebook',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
