# Generated by Django 4.2.23 on 2025-09-02 05:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('services', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('common', '0006_pages_type'),
        ('clients', '0002_alter_entreprise_page_facebook'),
        ('vente', '0002_delete_service'),
    ]

    operations = [
        migrations.CreateModel(
            name='Commande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statut_publication', models.CharField(choices=[('publié', 'Publié'), ('modifié', 'Modifié'), ('supprimé', 'Supprimé')], default='publié', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('numero_proforma', models.CharField(editable=False, max_length=20, unique=True)),
                ('date_commande', models.DateField(default=django.utils.timezone.now)),
                ('remarque', models.TextField(blank=True, null=True)),
                ('statut_vente', models.CharField(choices=[('En attente', 'En attente'), ('Planifiée', 'Planifiée'), ('Payée', 'Payée'), ('Livrée', 'Livrée'), ('Annulée', 'Annulée'), ('Reportée', 'Reportée'), ('Supprimée', 'Supprimée')], default='En attente', max_length=20)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.entreprise')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_created_%(class)s_set', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_deleted_%(class)s_set', to=settings.AUTH_USER_MODEL)),
                ('page', models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_commandes', to='common.pages')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_updated_%(class)s_set', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Vente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statut_publication', models.CharField(choices=[('publié', 'Publié'), ('modifié', 'Modifié'), ('supprimé', 'Supprimé')], default='publié', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('numero_facture', models.CharField(blank=True, editable=False, max_length=20, null=True, unique=True)),
                ('date_encaissement', models.DateField(default=django.utils.timezone.now)),
                ('reference', models.CharField(blank=True, max_length=50, null=True)),
                ('montant', models.PositiveIntegerField()),
                ('commande', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='vente', to='vente.commande')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_created_%(class)s_set', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_deleted_%(class)s_set', to=settings.AUTH_USER_MODEL)),
                ('paiement', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='service_ventes', to='common.caisse')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_updated_%(class)s_set', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LigneCommande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statut_publication', models.CharField(choices=[('publié', 'Publié'), ('modifié', 'Modifié'), ('supprimé', 'Supprimé')], default='publié', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tarif', models.PositiveIntegerField()),
                ('quantite', models.PositiveIntegerField()),
                ('commande', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes_commandes', to='vente.commande')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_created_%(class)s_set', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_deleted_%(class)s_set', to=settings.AUTH_USER_MODEL)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lignes_commandes', to='services.service')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_updated_%(class)s_set', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
